/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zh_ndk_basic_NativeClass */

#ifndef _Included_org_zh_ndk_basic_NativeClass
#define _Included_org_zh_ndk_basic_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zh_ndk_basic_NativeClass
 * Method:    max
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_zh_ndk_basic_NativeClass_max
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
